users:
  name: str
  preferred_hand: ["L", "R"]
  identified_gender: ["M", "F", "X", "N", "B"]
  test: bool
  group_id: ["A", "B"]


log:
  user: str
  target_seq: str
  pixel_size: int
  pixel_distance: int
  action: str
  expt_state: str
  



